[Variables]
;ToDoList
Item1=数分学习；数分作业
Item2=线代学习；线代作业
Item3=数分线代普化史纲考试
Item4=美国政治与外交的论文
Item5=思修网上学习论文
Item6=程设大作业
Item7=英美文学essay
Item8=史纲论文；史纲困惑解惑打印
Item9=每天写一篇日记,多喝水
Item10=不要挠自己！
Item11=每天开开心心的！
Item12=记得那些为你操心的人

Item2-1=#Item1#    
Item2-2=#Item2#         
Item2-3=#Item3#        
Item2-4=#Item4#         
Item2-5=#Item5#     
Item2-6=#Item6#    
Item2-7=#Item7#    
Item2-8=#Item8#  
Item2-9=#Item9#  
Item2-10=#Item10#   
Item2-11=#Item11#   
Item2-12=#Item12#   



FontColor=255,250,250
BackGroundColor=179,159,124,100
