[Variables]
;ToDoList
Item1=我想做的事情之一
Item2=我想做的事情之二
Item3=我想做的事情之三
Item4=我想做的事情之四
Item5=我想做的事情之五
Item6=我想做的事情之六
Item7=我想做的事情之七
Item8=我想做的事情之八
Item9=我想做的事情之九
Item10=我想做的事情之十
Item11=我想做的事情之十一
Item12=我想做的事情之十二

Item2-1=#Item1#   
Item2-2=#Item2#        
Item2-3=#Item3#       
Item2-4=#Item4#        
Item2-5=#Item5#    
Item2-6=#Item6#   
Item2-7=#Item7#   
Item2-8=#Item8# 
Item2-9=#Item9#
Item2-10=#Item10#  
Item2-11=#Item11#  
Item2-12=#Item12#  



FontColor=172,125,159
BackGroundColor=255,255,255,100
