[Variables]

Subfield1=雨滴工作用
Subfield2=软件工具
Subfield3=休闲娱乐
Subfield4=
Subfield5=
Subfield6=
Subfield7=
Subfield8=
Subfield9=
Subfield10=

G11=Druid\25.png
Path11=C:\Users\Administrator\Documents\Rainmeter\Skins\hearthstone
T11=皮肤文件夹

G12=Druid\23.png
Path12=D:\rainmeter空间\Rainmeter中文手册第四版.pdf
T12=中文手册

G13=Druid\13.png
Path13=F:\BaiduYunDownload\资源
T13=炉石资源

G14=Druid\
Path14=
T14=

G15=Druid\
Path15=
T15=

G16=Druid\
Path16=
T16=

G17=Druid\
Path17=
T17=

G18=Druid\
Path18=
T18=

G21=Hunter\25.png
Path21=D:\software\photoshop\mainbody\Adobe Photoshop CC (64 Bit)\Photoshop.exe
T21=photoshop

G22=Hunter\24.png
Path22=D:\software\formatfactory\mainbody\FormatFactory.exe
T22=格式工厂

G23=Hunter\23
Path23=D:\software\baiduyun\BaiduYunGuanjia\BaiduYunGuanjia.exe
T23=百度云

G24=Hunter\
Path24=
T24=

G25=Hunter\
Path25=
T25=

G26=Hunter\
Path26=
T26=

G27=Hunter\
Path27=
T27=

G28=Hunter\
Path28=
T28=

G31=Mage\24.png
Path31=D:\software\winamp\Winamp\winamp.exe
T31=winamp

G32=Mage\25.png
Path32=E:\cs1.6\cstrike.exe
T32=CS1.6

G33=Mage\23.png
Path33=E:\guildwar\GuildWars2\Gw2.exe
T33=激战2

G34=Mage\
Path34=
T34=

G35=Mage\
Path35=
T35=

G36=Mage\
Path36=
T36=

G37=Mage\
Path37=
T37=

G38=Mage\
Path38=
T38=

G41=Paladin\
Path41=
T41=

G42=Paladin\
Path42=
T42=

G43=Paladin\
Path43=
T43=

G44=Paladin\
Path44=
T44=

G45=Paladin\
Path45=
T45=

G46=Paladin\
Path46=
T46=

G47=Paladin\
Path47=
T47=

G48=Paladin\
Path48=
T48=

G51=Priest\
Path51=
T51=

G52=Priest\
Path52=
T52=

G53=Priest\
Path53=
T53=

G54=Priest\
Path54=
T54=

G55=Priest\
Path55=
T55=

G56=Priest\
Path56=
T56=

G57=Priest\
Path57=
T57=

G58=Priest\
Path58=
T58=

G61=Rogue\
Path61=
T61=

G62=Rogue\
Path62=
T62=

G63=Rogue\
Path63=
T63=

G64=Rogue\
Path64=
T64=

G65=Rogue\
Path65=
T65=

G66=Rogue\
Path66=
T66=

G67=Rogue\
Path67=
T67=

G68=Rogue\
Path68=
T68=

G71=Shaman\
Path71=
T71=

G72=Shaman\
Path72=
T72=

G73=Shaman\
Path73=
T73=

G74=Shaman\
Path74=
T74=

G75=Shaman\
Path75=
T75=

G76=Shaman\
Path76=
T76=

G77=Shaman\
Path77=
T77=

G78=Shaman\
Path78=
T78=

G81=Warlock\
Path81=
T81=

G82=Warlock\
Path82=
T82=

G83=Warlock\
Path83=
T83=

G84=Warlock\
Path84=
T84=

G85=Warlock\
Path85=
T85=

G86=Warlock\
Path86=
T86=

G87=Warlock\
Path87=
T87=

G88=Warlock\
Path88=
T88=

G91=Warrior\
Path91=
T91=

G92=Warrior\
Path92=
T92=

G93=Warrior\
Path93=
T93=

G94=Warrior\
Path94=
T94=

G95=Warrior\
Path95=
T95=

G96=Warrior\
Path96=
T96=

G97=Warrior\
Path97=
T97=

G98=Warrior\
Path98=
T98=

G101=Any\
Path101=
T101=

G102=Any\
Path102=
T102=

G103=Any\
Path103=
T103=

G104=Any\
Path104=
T104=

G105=Any\
Path105=
T105=

G106=Any\
Path106=
T106=

G107=Any\
Path107=
T107=

G108=Any\
Path108=
T108=